/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import FuncionalidadesGUI.PanelDeOpcciones;
import javax.swing.JOptionPane;

/**
 *
 * @author baquiax
 */
public class Inicio extends javax.swing.JFrame {

    private PanelDeOpcciones opciones;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        opciones = new PanelDeOpcciones();
        initComponents();
        super.setLayout(null);
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jmb1 = new javax.swing.JMenuBar();
        jmn1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador");

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        jScrollPane1.setViewportView(txtTexto);

        jmn1.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("/home/baquiax/Documentos/Programas de Curso/Lenguajes/FinalLenguajes/ProyectoFinal/src/main/resources/open.png")); // NOI18N
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmn1.add(jMenuItem1);
        jmn1.add(jSeparator1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("/home/baquiax/Documentos/Programas de Curso/Lenguajes/FinalLenguajes/ProyectoFinal/src/main/resources/save.png")); // NOI18N
        jMenuItem2.setText("Guardar");
        jmn1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("/home/baquiax/Documentos/Programas de Curso/Lenguajes/FinalLenguajes/ProyectoFinal/src/main/resources/saveAs.png")); // NOI18N
        jMenuItem3.setText("Guardar Como");
        jmn1.add(jMenuItem3);

        jmb1.add(jmn1);

        jMenu2.setText("Acerca De");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jMenuItem4.setText("Acerca De");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jmb1.add(jMenu2);

        setJMenuBar(jmb1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, opciones.abrirArchivo(), "Acerca De", JOptionPane.INFORMATION_MESSAGE);
        txtTexto.setText(opciones.getTexto());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Creado por Ludvin Nicolas Basilio Baquiax Vasquez", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar jmb1;
    private javax.swing.JMenu jmn1;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
